DROP TABLE IF EXISTS city;

CREATE TABLE city (
id INT AUTO_INCREMENT  PRIMARY KEY,
city_name VARCHAR(50) NOT NULL,
city_pincode INT NOT NULL
);

DROP TABLE IF EXISTS citizen;

CREATE TABLE citizen (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
surname INT NOT NULL,
birthdate DATE NOT NULL,
fiscal_code VARCHAR(16) UNIQUE NOT NULL,
address VARCHAR(100) NOT NULL,
id_number VARCHAR(10) UNIQUE NOT NULL
);
