DROP TABLE IF EXISTS city;

CREATE TABLE city (
id INT AUTO_INCREMENT  PRIMARY KEY,
city_name VARCHAR(50) NOT NULL,
city_pin_code INT NOT NULL
);

CREATE TABLE citizen (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
birthdate DATE NOT NULL,
fiscal_code VARCHAR(16) NOT NULL UNIQUE,
address VARCHAR(150) NOT NULL,
id_number VARCHAR(9) NOT NULL UNIQUE
)